olympic_train_output_dir: 'olympic_project/data/train_dir.csv'
olympic_train_desired_name: 'olympic_project/data/train.csv'
olympic_test_output_dir: 'olympic_project/data/test_dir.csv'
olympic_test_desired_name: 'olympic_project/data/test.csv'